/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizadorcomplejidadtemporal.vistas;

/**
 *
 * @author Admin
 */
public class PantallaSeleccion extends javax.swing.JFrame {

    private final java.util.List<String> algoritmosSeleccionados = new java.util.ArrayList<>();
    private final java.util.Map<javax.swing.JButton, String> nombresAlgoritmos = new java.util.HashMap<>();
    private javax.swing.JButton btnBusquedaCentinela;

    private void inicializarAlgoritmos() {
        nombresAlgoritmos.put(btnBusquedaLineal, "Búsqueda Lineal");
        nombresAlgoritmos.put(btnBusquedaBinaria, "Búsqueda Binaria");
        nombresAlgoritmos.put(btnFibonacciIterativo, "Fibonacci Iterativo");
        nombresAlgoritmos.put(btnPotenciaIterativo, "Potencia Iterativa");
        nombresAlgoritmos.put(btnFactorialIterativo, "Factorial Iterativo");
        nombresAlgoritmos.put(btnFibonacciRecursivo, "Fibonacci Recursivo");
        nombresAlgoritmos.put(btnPotenciaRecursivo, "Potencia Recursiva");
        nombresAlgoritmos.put(btnFactorialRecursivo, "Factorial Recursivo");
        
        // Deshabilitar el botón de Siguiente al inicio porque la selección es 0 (mínimo 2)
        btnSiguienteHaciaSeleccionTamaño.setEnabled(false);
    }

    /**
     * Agrega el botón de Búsqueda Centinela programáticamente.
     */
    private void agregarBotonCentinela() {
        btnBusquedaCentinela = new javax.swing.JButton();
        btnBusquedaCentinela.setBackground(new java.awt.Color(30, 41, 59));
        btnBusquedaCentinela.setFont(new java.awt.Font("Segoe UI", 1, 20));
        btnBusquedaCentinela.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaCentinela.setText("Busqueda Centinela");
        btnBusquedaCentinela.addActionListener(e -> alternarSeleccion(btnBusquedaCentinela));
        jPanel1.add(btnBusquedaCentinela, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 240, 80));
        nombresAlgoritmos.put(btnBusquedaCentinela, "Búsqueda Centinela");
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * Determina si un algoritmo es de tipo búsqueda.
     */
    private boolean esBusqueda(String nombre) {
        return nombre.contains("Búsqueda");
    }

    private void alternarSeleccion(javax.swing.JButton boton) {
        String nombre = nombresAlgoritmos.get(boton);
        if (nombre == null) return;

        if (algoritmosSeleccionados.contains(nombre)) {
            // Deseleccionar
            algoritmosSeleccionados.remove(nombre);
            boton.setBackground(new java.awt.Color(30, 41, 59));
            boton.setForeground(java.awt.Color.WHITE);
        } else {
            // Seleccionar (máximo 3)
            if (algoritmosSeleccionados.size() < 3) {
                algoritmosSeleccionados.add(nombre);
                boton.setBackground(new java.awt.Color(0, 204, 204));
                boton.setForeground(new java.awt.Color(18, 24, 36));
            }
        }

        // Actualizar el texto del contador
        txtSeleccionadosCuenta.setText(String.valueOf(algoritmosSeleccionados.size()));

        // Validar si el botón Siguiente debe estar habilitado
        boolean seleccionValida = algoritmosSeleccionados.size() >= 2 && algoritmosSeleccionados.size() <= 3;
        btnSiguienteHaciaSeleccionTamaño.setEnabled(seleccionValida);

        // Bloquear los demás botones si ya se seleccionaron 3
        boolean limiteAlcanzado = algoritmosSeleccionados.size() == 3;
        for (javax.swing.JButton btn : nombresAlgoritmos.keySet()) {
            String name = nombresAlgoritmos.get(btn);
            if (!algoritmosSeleccionados.contains(name)) {
                btn.setEnabled(!limiteAlcanzado);
            }
        }
    }

    /**
     * Creates new form PantallaSeleccion
     */
    public PantallaSeleccion() {
        initComponents();
        inicializarAlgoritmos();
        agregarBotonCentinela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnSiguienteHaciaSeleccionTamaño = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtTituloSeleccionDeAlgoritmos = new javax.swing.JLabel();
        txtSeleccionadosCuenta = new javax.swing.JLabel();
        txtTituloAlogritmosBusqueda = new javax.swing.JLabel();
        txtTituloAlgoritmosIterativos = new javax.swing.JLabel();
        btnBusquedaBinaria = new javax.swing.JButton();
        btnBusquedaLineal = new javax.swing.JButton();
        btnFibonacciRecursivo = new javax.swing.JButton();
        btnPotenciaRecursivo = new javax.swing.JButton();
        btnFactorialRecursivo = new javax.swing.JButton();
        txtTituloAlgoritmosRecursivos = new javax.swing.JLabel();
        txtSele = new javax.swing.JLabel();
        btnFibonacciIterativo = new javax.swing.JButton();
        btnPotenciaIterativo = new javax.swing.JButton();
        btnFactorialIterativo = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(18, 24, 36));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proyecto final");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 19, 1080, 120));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(18, 24, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(18, 24, 36));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguienteHaciaSeleccionTamaño.setBackground(new java.awt.Color(30, 41, 59));
        btnSiguienteHaciaSeleccionTamaño.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSiguienteHaciaSeleccionTamaño.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteHaciaSeleccionTamaño.setText("Siguiente");
        btnSiguienteHaciaSeleccionTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteHaciaSeleccionTamañoActionPerformed(evt);
            }
        });
        jPanel4.add(btnSiguienteHaciaSeleccionTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 240, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1090, 120));

        jPanel3.setBackground(new java.awt.Color(18, 24, 36));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloSeleccionDeAlgoritmos.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        txtTituloSeleccionDeAlgoritmos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloSeleccionDeAlgoritmos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloSeleccionDeAlgoritmos.setText("Selección de Algoritmos ");
        jPanel3.add(txtTituloSeleccionDeAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1080, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, 140));

        txtSeleccionadosCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSeleccionadosCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtSeleccionadosCuenta.setText("0");
        jPanel1.add(txtSeleccionadosCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 160, 40));

        txtTituloAlogritmosBusqueda.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloAlogritmosBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloAlogritmosBusqueda.setText("Algoritmos de busqueda");
        jPanel1.add(txtTituloAlogritmosBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 290, 40));

        txtTituloAlgoritmosIterativos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloAlgoritmosIterativos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloAlgoritmosIterativos.setText("Algoritmos Iterativos");
        jPanel1.add(txtTituloAlgoritmosIterativos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 250, 40));

        btnBusquedaBinaria.setBackground(new java.awt.Color(30, 41, 59));
        btnBusquedaBinaria.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBusquedaBinaria.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaBinaria.setText("Busqueda Binaria");
        btnBusquedaBinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaBinariaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusquedaBinaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 240, 80));

        btnBusquedaLineal.setBackground(new java.awt.Color(30, 41, 59));
        btnBusquedaLineal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBusquedaLineal.setForeground(new java.awt.Color(255, 255, 255));
        btnBusquedaLineal.setText("Busqueda Lineal");
        btnBusquedaLineal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaLinealActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusquedaLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 240, 80));

        btnFibonacciRecursivo.setBackground(new java.awt.Color(30, 41, 59));
        btnFibonacciRecursivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFibonacciRecursivo.setForeground(new java.awt.Color(255, 255, 255));
        btnFibonacciRecursivo.setText("Fibonacci");
        btnFibonacciRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciRecursivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFibonacciRecursivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 240, 80));

        btnPotenciaRecursivo.setBackground(new java.awt.Color(30, 41, 59));
        btnPotenciaRecursivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPotenciaRecursivo.setForeground(new java.awt.Color(255, 255, 255));
        btnPotenciaRecursivo.setText("Potencia");
        btnPotenciaRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaRecursivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPotenciaRecursivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 240, 80));

        btnFactorialRecursivo.setBackground(new java.awt.Color(30, 41, 59));
        btnFactorialRecursivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFactorialRecursivo.setForeground(new java.awt.Color(255, 255, 255));
        btnFactorialRecursivo.setText("Factorial");
        btnFactorialRecursivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialRecursivoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactorialRecursivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 240, 80));

        txtTituloAlgoritmosRecursivos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTituloAlgoritmosRecursivos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloAlgoritmosRecursivos.setText("Algoritmos Recursivos");
        jPanel1.add(txtTituloAlgoritmosRecursivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 270, 40));

        txtSele.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtSele.setForeground(new java.awt.Color(255, 255, 255));
        txtSele.setText("Seleccionados:");
        jPanel1.add(txtSele, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 180, 40));

        btnFibonacciIterativo.setBackground(new java.awt.Color(30, 41, 59));
        btnFibonacciIterativo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFibonacciIterativo.setForeground(new java.awt.Color(255, 255, 255));
        btnFibonacciIterativo.setText("Fibonacci");
        btnFibonacciIterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciIterativoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFibonacciIterativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 240, 80));

        btnPotenciaIterativo.setBackground(new java.awt.Color(30, 41, 59));
        btnPotenciaIterativo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPotenciaIterativo.setForeground(new java.awt.Color(255, 255, 255));
        btnPotenciaIterativo.setText("Potencia");
        btnPotenciaIterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaIterativoActionPerformed(evt);
            }
        });
        jPanel1.add(btnPotenciaIterativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 240, 80));

        btnFactorialIterativo.setBackground(new java.awt.Color(30, 41, 59));
        btnFactorialIterativo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFactorialIterativo.setForeground(new java.awt.Color(255, 255, 255));
        btnFactorialIterativo.setText("Factorial");
        btnFactorialIterativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialIterativoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactorialIterativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 240, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaBinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaBinariaActionPerformed
        alternarSeleccion(btnBusquedaBinaria);
    }//GEN-LAST:event_btnBusquedaBinariaActionPerformed

    private void btnSiguienteHaciaSeleccionTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteHaciaSeleccionTamañoActionPerformed
        PantallaSeleccionTamañoArreglo pantalla = new PantallaSeleccionTamañoArreglo(algoritmosSeleccionados);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteHaciaSeleccionTamañoActionPerformed

    private void btnBusquedaLinealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaLinealActionPerformed
        alternarSeleccion(btnBusquedaLineal);
    }//GEN-LAST:event_btnBusquedaLinealActionPerformed

    private void btnFibonacciRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciRecursivoActionPerformed
        alternarSeleccion(btnFibonacciRecursivo);
    }//GEN-LAST:event_btnFibonacciRecursivoActionPerformed

    private void btnPotenciaRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaRecursivoActionPerformed
        alternarSeleccion(btnPotenciaRecursivo);
    }//GEN-LAST:event_btnPotenciaRecursivoActionPerformed

    private void btnFactorialRecursivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialRecursivoActionPerformed
        alternarSeleccion(btnFactorialRecursivo);
    }//GEN-LAST:event_btnFactorialRecursivoActionPerformed

    private void btnFibonacciIterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciIterativoActionPerformed
        alternarSeleccion(btnFibonacciIterativo);
    }//GEN-LAST:event_btnFibonacciIterativoActionPerformed

    private void btnPotenciaIterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaIterativoActionPerformed
        alternarSeleccion(btnPotenciaIterativo);
    }//GEN-LAST:event_btnPotenciaIterativoActionPerformed

    private void btnFactorialIterativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialIterativoActionPerformed
        alternarSeleccion(btnFactorialIterativo);
    }//GEN-LAST:event_btnFactorialIterativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusquedaBinaria;
    private javax.swing.JButton btnBusquedaLineal;
    private javax.swing.JButton btnFactorialIterativo;
    private javax.swing.JButton btnFactorialRecursivo;
    private javax.swing.JButton btnFibonacciIterativo;
    private javax.swing.JButton btnFibonacciRecursivo;
    private javax.swing.JButton btnPotenciaIterativo;
    private javax.swing.JButton btnPotenciaRecursivo;
    private javax.swing.JButton btnSiguienteHaciaSeleccionTamaño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtSele;
    private javax.swing.JLabel txtSeleccionadosCuenta;
    private javax.swing.JLabel txtTituloAlgoritmosIterativos;
    private javax.swing.JLabel txtTituloAlgoritmosRecursivos;
    private javax.swing.JLabel txtTituloAlogritmosBusqueda;
    private javax.swing.JLabel txtTituloSeleccionDeAlgoritmos;
    // End of variables declaration//GEN-END:variables
}
