/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package analizadorcomplejidadtemporal.vistas;

/**
 *
 * @author Admin
 */
public class PantallaSeleccionTamañoArreglo extends javax.swing.JFrame {

    /**
     * Creates new form PantallaSeleccionTamañoArreglo
     */
    public PantallaSeleccionTamañoArreglo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTituloSeleccionDeAlgoritmos = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn10000 = new javax.swing.JButton();
        btn100000 = new javax.swing.JButton();
        btnSiguienteHaciaResultados = new javax.swing.JButton();
        btn500001 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(18, 24, 36));

        jPanel1.setBackground(new java.awt.Color(18, 24, 36));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(18, 24, 36));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloSeleccionDeAlgoritmos.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        txtTituloSeleccionDeAlgoritmos.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloSeleccionDeAlgoritmos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTituloSeleccionDeAlgoritmos.setText("Selección de tamaño del arreglo");
        jPanel3.add(txtTituloSeleccionDeAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 140));

        btn100.setBackground(new java.awt.Color(30, 41, 59));
        btn100.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("100");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 240, 80));

        btn1000.setBackground(new java.awt.Color(30, 41, 59));
        btn1000.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn1000.setForeground(new java.awt.Color(255, 255, 255));
        btn1000.setText("1000");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 240, 80));

        btn10000.setBackground(new java.awt.Color(30, 41, 59));
        btn10000.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn10000.setForeground(new java.awt.Color(255, 255, 255));
        btn10000.setText("10000");
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 240, 80));

        btn100000.setBackground(new java.awt.Color(30, 41, 59));
        btn100000.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn100000.setForeground(new java.awt.Color(255, 255, 255));
        btn100000.setText("100000");
        btn100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100000ActionPerformed(evt);
            }
        });
        jPanel1.add(btn100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 240, 80));

        btnSiguienteHaciaResultados.setBackground(new java.awt.Color(30, 41, 59));
        btnSiguienteHaciaResultados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSiguienteHaciaResultados.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteHaciaResultados.setText("Siguiente");
        btnSiguienteHaciaResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteHaciaResultadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguienteHaciaResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 570, 240, 80));

        btn500001.setBackground(new java.awt.Color(30, 41, 59));
        btn500001.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn500001.setForeground(new java.awt.Color(255, 255, 255));
        btn500001.setText("500000");
        btn500001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500001ActionPerformed(evt);
            }
        });
        jPanel1.add(btn500001, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 240, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btnSiguienteHaciaResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteHaciaResultadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteHaciaResultadosActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn100000ActionPerformed

    private void btn500001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500001ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn500001ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccionTamañoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccionTamañoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccionTamañoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSeleccionTamañoArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSeleccionTamañoArreglo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn100000;
    private javax.swing.JButton btn500001;
    private javax.swing.JButton btnSiguienteHaciaResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtTituloSeleccionDeAlgoritmos;
    // End of variables declaration//GEN-END:variables
}
